logging.level:
  root: INFO
  pe.perico.client: DEBUG
  org.springframework.web: DEBUG
  com.microsoft: ERROR

server:
  port: 8080

spring:
  jackson:
    time-zone: America/Lima
    locale: es_PE
  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.SQLServer2014Dialect
    open-in-view: false
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=pericodb;loginTimeout=30;
    username: sa
    password: PasswordO1.
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

management:
  endpoints:
    web:
      exposure:
        include: health, perico-client-features

opentracing:
  jaeger:
    enabled: true
    enable-b3-propagation: true
    log-spans: true
    const-sampler:
      decision: true
    http-sender:
      url: http://localhost:14268/api/traces