logging.level:
  root: INFO
  pe.perico.client: DEBUG
  org.springframework.web: DEBUG
  com.microsoft: ERROR

server:
  port: 8080

spring:
  jackson:
    time-zone: America/Lima
    locale: es_PE
  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.SQLServer2014Dialect
    open-in-view: false
  datasource:
    url: jdbc:sqlserver://integrator-utp.database.windows.net:1433;database=pericodb;user=sqlserver@integrator-utp;password={your_password_here};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: sqlserver
    password: sudopassword11!
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

management:
  endpoints:
    web:
      exposure:
        include: health, perico-client-features